# Generated by Django 4.1.7 on 2023-03-30 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_photo_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='image',
            new_name='photo',
        ),
    ]
