# Generated by Django 4.1.7 on 2023-03-30 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='avatar',
        ),
    ]
